# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Siân Tunstall's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Siân TUNSTALL
headline: R&D Formulation Chemist
description: >- # dont remove this line. this will ignore all new lines until the next section
 <p align="justify"> Hello, and welcome to my portfolio!

  I created this webpage to showcase what I can bring to your company as a formulation chemist. Please feel free to peruse my projects and initiatives that I have detailed below.<br/>
  I am not afraid of going above and beyond what is asked for, if it can benefit the project and the team (like creating an online portfolio almost from scratch). My curiosity and perseverance help me dive into projects, understand what is needed and plan what my team and I can do to reach our goals.</p>



# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/Photo_CV.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1JFg6EiXZmSVSU2yfmFY5-s1o0M0ch2VZ/view?usp=drive_link


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: siantunstall    # https://www.linkedin.com/in/{your url slug} 
  github:     # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Genral Formulation
    tools:
    - Direct and indirect emulsions
    - Microemulsions
    - Designing and respecting specifications
    - Industrial and lab scale mixing
  - category: General Caracterisation
    tools:
    - Rheology (viscoelastic spectrum, Brookfield)
    - Mechanical tests (traction, friction, hardness)
    - Sensory analysis (touch, smell and taste)
  - category: Analytical Chemistry
    tools:
    - HPLC
    - GPC
    - DSC
    - TGA
    - DMA
    - IR-FTIR
    - Granulometry
  - category: Polymers
    tools:
    - Polyesters
    - Polyurethanes
    - Extrusion
    - Melt Flow Index
    - Thermosealing (application and characterisation)
    - Kinetic studies
  - category: Computer Skills
    tools:
    - Microsoft Office (Word, Powerpoint, Excel)
    - Microsoft Teams
    - Outlook
    - GANTT Charts
    - Python (numpy, pandas, scikit-learn, RDKit)
    - SQL 
  - category: Adhesives
    tools:
    - Reactive and non-reactive adhesives
    - 1K and 2K formulations
    - Adhesive coating formulation, application and characterisation
    - Bond strength tests
    - DSC, ATG and DMA Analysis
# Contact Form Setup. Setup an account and c
  - category: Paints and Pigments
    tools:
    - Water and solvent based
    - 1K and 2K formulations
    - Gloss and colour
    - Misc. caracterisations (syneresis, gel, sedimentation, flow threshold)
  - category: Health & Safety
    tools:
    - 5S method (Sort, Set in order, Shine, Sustain, Self-Discipline)
    - Hazard Analysis Critical Control Point (HACCP)
    - Health and safety analysis of new methods and protocoles

formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
